### PR TITLE
Various Slime Fixes

### LINKED ISSUE #238: ticon slime's readFromNBT resets health.
### Your GTNH Discord Username

_No response_

### Mod Version

latest

### Bug Report

When readFromNBT is called, it calls setSlimeSize which resets health. This makes reloading the slime or changing the slime's dimension reset health.

### Java Version

Java 8

### Mod List or GTNH Pack Version

Tinkers

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.

### LINKED ISSUE #239: Slime xp scaling is incorrect
### Your GTNH Discord Username

_No response_

### Mod Version

latest

### Bug Report

Slime xp scaling used bitwise xor instead of Math.pow. 

### Java Version

Java 8

### Mod List or GTNH Pack Version

ticon

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.

### LINKED ISSUE #240: Ticon Slimes do not extend vanilla slimes
### Your GTNH Discord Username

_No response_

### Mod Version

latest

### Bug Report

Ticon slimes do not do not extend vanilla slimes. I believe they are a eula violation. This also leads to worse compat.

### Java Version

Java 8

### Mod List or GTNH Pack Version

Tinkers

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.

### LINKED ISSUE #241: King Slimes have incorrect XP.
### Your GTNH Discord Username

_No response_

### Mod Version

latest

### Bug Report

King Slimes have their experience set to 500. This is overwritten by setSlimeSize. They should either not set their experience to 500 or they should not have setSlimeSize overwrite it.

### Java Version

Java 8

### Mod List or GTNH Pack Version

Tinkers

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.

### PR DESCRIPTION
**Pull request by ohentis**
Fixes #241 Fixes #240 Fixes #239 Fixes  #238

### CODE REVIEW

File: src/main/java/tconstruct/world/entity/SlimeBase.java [hunk 1]
```diff
@@ -380,26 +269,14 @@ protected float getSoundVolume() {
...
-    }
 
     /**
      * (abstract) Protected helper method to read subclass entity data from NBT.
      */
     @Override
     public void readEntityFromNBT(NBTTagCompound par1NBTTagCompound) {
         super.readEntityFromNBT(par1NBTTagCompound);
-        this.setSlimeSize(par1NBTTagCompound.getInteger("Size") + 1);
+        this.setHealth(this.oldHealth);
```
Comment (danyadev) [inline src/main/java/tconstruct/world/entity/SlimeBase.java]: health reset is already fixed for minecraft's EntitySlime itself:
https://github.com/GTNewHorizons/Hodgepodge/pull/704
